### ISSUE TITLE
Refresh reloads the quiestionnaire

### ISSUE THREAD

**Issue by chahat** [mitchgavan/react-multi-choice-quiz#5]
How to remember the state of the questionnaire so that upon reload the questionnaire is not reloaded from start ?

I am building an app using your code. Would you happen to know more production oriented codebase for the same? with features like 
questionaire generator, saving the state so reload does not refreshes, time based questionnaire

in short i am looking for a more production quality solution. Please let em know if you are aware of any with MIT/GPU license

**Comment by mitchgavan** [comment]
You could persist the data to localStorage or a database. Feel free to do whatever you like with this code.
