### ISSUE TITLE
Correct-Incorrect Multiple Choice question

### ISSUE THREAD

**Issue by parthu21** [mitchgavan/react-multi-choice-quiz#6]
Hi Mitch,
Thanks for this beginner-friendly project. I was updating it to handle multiple choice questions which have correct-incorrect options with an increase in score by 10 on correct answer and 0 on incorrect one. I tried it by adding a score parameter in the state space and updated other functions similarly. I also changed the quizQuestions.js similarly adding a correct answer and removing key from answer choices. But it's not detecting or updating on any event on the webpage?
Can you please take a quick look and point out what am I doing wrong? 
I am also attaching App.js(as App.txt) and quizQuestions.js(as .txt), I hope this don't take much of your time.
[App.txt](https://github.com/mitchgavan/react-multi-choice-quiz/files/4232870/App.txt)
[quizQuestions.txt](https://github.com/mitchgavan/react-multi-choice-quiz/files/4232873/quizQuestions.txt)

**Comment by mitchgavan** [comment]
Hi, unfortunately I don't have time to review this. Since it's not an issue with the source code I'm closing.
